'use client';

import React, { useEffect, useState } from 'react';
import Sidebar from '../../components/Sidebar';
import { useAuth } from '../../context/AuthContext';
import { History, Activity, AlertTriangle, ShieldCheck, HelpCircle, Trash2 } from 'lucide-react';

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'https://transformer-camera-api.maxapi.esp32.site';

export default function HistoryPage() {
  const { user } = useAuth();
  const [events, setEvents] = useState<any[]>([]);
  const [devices, setDevices] = useState<any[]>([]);
  const [selectedFilterDevice, setSelectedFilterDevice] = useState<string>('all');
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');

  const handleDeleteEvent = async (eventId: string) => {
    if (!confirm('Are you sure you want to delete this threat incident log?')) return;
    try {
      const res = await fetch(`${BACKEND_URL}/api/events/${eventId}?userId=${user?.uid}`, {
        method: 'DELETE'
      });
      const data = await res.json();
      if (data.success) {
        setEvents(prev => prev.filter(e => e._id !== eventId));
      } else {
        alert(data.error || 'Failed to delete event log.');
      }
    } catch (err: any) {
      console.error('Error deleting event log:', err);
    }
  };

  const deviceMap = React.useMemo(() => {
    const map: Record<string, string> = {};
    devices.forEach((d) => {
      map[d.uid.toUpperCase()] = d.deviceName;
    });
    return map;
  }, [devices]);

  const fetchDevices = async () => {
    if (!user) return;
    try {
      const res = await fetch(`${BACKEND_URL}/api/devices/${user.uid}`);
      const data = await res.json();
      setDevices(data.devices || []);
    } catch (err) {
      console.error(err);
    }
  };

  const fetchEvents = async () => {
    if (!user) return;
    try {
      setLoading(true);
      const res = await fetch(`${BACKEND_URL}/api/events/${user.uid}`);
      const data = await res.json();
      setEvents(data.events || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (user) {
      fetchEvents();
      fetchDevices();
    }
  }, [user]);

  // Filter events based on active score range
  const filteredEvents = events.filter((e) => {
    if (selectedFilterDevice !== 'all' && e.uid.toUpperCase() !== selectedFilterDevice.toUpperCase()) {
      return false;
    }
    if (filter === 'critical') return e.threatScore >= 80;
    if (filter === 'warning') return e.threatScore >= 50 && e.threatScore < 80;
    if (filter === 'safe') return e.threatScore < 50;
    return true;
  });

  return (
    <div className="flex flex-col lg:flex-row min-h-screen bg-base-300">
      <Sidebar />

      <main className="flex-1 p-4 lg:p-8 overflow-y-auto max-h-screen w-full">
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 mb-8">
          <div>
            <h2 className="text-3xl font-extrabold tracking-tight text-base-content">Threat History &amp; Archives</h2>
            <p className="text-sm text-base-content/80">Audit historical security logs and analysis details generated by the AI agent.</p>
          </div>

          <div className="flex gap-3 items-center">
            <select
              value={selectedFilterDevice}
              onChange={(e) => setSelectedFilterDevice(e.target.value)}
              className="select select-bordered select-sm rounded-xl bg-base-200 text-xs font-semibold border-base-100/50 text-base-content"
            >
              <option value="all">All Devices</option>
              {devices.map(d => (
                <option key={d.uid} value={d.uid}>{d.deviceName}</option>
              ))}
            </select>

            <div className="tabs tabs-boxed bg-base-200">
              <button 
                onClick={() => setFilter('all')} 
                className={`tab tab-sm font-semibold rounded-xl ${filter === 'all' ? 'tab-active bg-primary text-primary-content' : ''}`}
              >
                All Events
              </button>
              <button 
                onClick={() => setFilter('critical')} 
                className={`tab tab-sm font-semibold rounded-xl ${filter === 'critical' ? 'tab-active bg-primary text-primary-content' : ''}`}
              >
                High Risk (80+)
              </button>
              <button 
                onClick={() => setFilter('warning')} 
                className={`tab tab-sm font-semibold rounded-xl ${filter === 'warning' ? 'tab-active bg-primary text-primary-content' : ''}`}
              >
                Warning (50-79)
              </button>
              <button 
                onClick={() => setFilter('safe')} 
                className={`tab tab-sm font-semibold rounded-xl ${filter === 'safe' ? 'tab-active bg-primary text-primary-content' : ''}`}
              >
                Normal (&lt;50)
              </button>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="flex h-[50vh] justify-center items-center">
            <span className="loading loading-spinner loading-lg text-primary"></span>
          </div>
        ) : filteredEvents.length === 0 ? (
          <div className="hero bg-base-200 border border-base-100 rounded-3xl p-12 text-center shadow-inner">
            <div className="hero-content flex-col max-w-md">
              <History className="w-16 h-16 text-primary/45 mb-2" />
              <h3 className="text-2xl font-bold">No History Logs Found</h3>
              <p className="py-2 text-sm text-base-content/80">
                No events have occurred matching this filter criteria.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {filteredEvents.map((evt) => {
              let headerStyle = 'border-l-4 border-l-base-content/30';
              let badgeColor = 'badge-ghost';
              let Icon = HelpCircle;
              
              if (evt.threatScore >= 80) {
                headerStyle = 'border-l-4 border-l-error';
                badgeColor = 'badge-error text-error-content';
                Icon = AlertTriangle;
              } else if (evt.threatScore >= 50) {
                headerStyle = 'border-l-4 border-l-warning';
                badgeColor = 'badge-warning text-warning-content';
                Icon = AlertTriangle;
              } else {
                headerStyle = 'border-l-4 border-l-success';
                badgeColor = 'badge-success text-success-content';
                Icon = ShieldCheck;
              }

              return (
                <div key={evt._id} className={`card bg-base-200 border border-base-100 shadow-xl overflow-hidden ${headerStyle}`}>
                  <div className="card-body p-6">
                    {/* Event Meta */}
                    <div className="flex justify-between items-start mb-4">
                      <div className="flex items-center gap-3">
                        <div className={`p-2.5 rounded-xl ${evt.threatScore >= 50 ? 'bg-error/10 text-error' : 'bg-success/10 text-success'}`}>
                          <Icon className="w-6 h-6" />
                        </div>
                        <div>
                          <h3 className="font-bold text-lg text-base-content leading-snug">{evt.message}</h3>
                          <p className="text-xs text-base-content/75 font-mono mt-0.5">{evt.time} | Device: {deviceMap[evt.uid.toUpperCase()] || evt.uid}</p>
                        </div>
                      </div>
                      <div className="flex flex-col items-end gap-1.5">
                        <div className="flex items-center gap-2">
                          <span className={`badge ${badgeColor} font-bold text-xs py-2 px-3`}>
                            Score: {evt.threatScore}%
                          </span>
                          {user?.role === 'admin' && (
                            <button
                              onClick={() => handleDeleteEvent(evt._id)}
                              className="btn btn-xs btn-circle btn-ghost text-error hover:bg-error/20"
                              title="Delete this incident log (Admin only)"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          )}
                        </div>
                        <span className="text-xs text-base-content/70 font-semibold uppercase">Zone: {evt.zoneCode}</span>
                      </div>
                    </div>

                    {/* AI analysis */}
                    <div className="space-y-2 mt-2">
                      <h4 className="font-bold text-sm text-base-content/80">AI Threat Analysis:</h4>
                      <p className="text-sm bg-base-300 p-4 rounded-xl leading-relaxed text-base-content/70">
                        {evt.aiReport}
                      </p>
                    </div>

                    {/* Burst Pictures */}
                    {evt.capturedImages && evt.capturedImages.length > 0 && (
                      <div className="mt-4">
                        <h4 className="font-bold text-sm text-base-content/80 mb-3">Snapshots Captured:</h4>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                          {evt.capturedImages.map((img: string, idx: number) => (
                            <div key={idx} className="aspect-video bg-neutral rounded-xl overflow-hidden relative shadow border border-base-100 group">
                              <a href={img} target="_blank" rel="noopener noreferrer">
                                <img 
                                  src={img} 
                                  alt={`Snapshot Frame ${idx+1}`} 
                                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" 
                                />
                                <div className="absolute top-2 left-2 bg-black/60 text-white font-semibold text-2xs px-2 py-0.5 rounded-md">
                                  Frame {idx+1}
                                </div>
                              </a>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
